-- ==========================================
-- 006_chat_and_communications.sql
-- Chat Messages History with Guest Support
-- ==========================================

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    guest_session_id TEXT,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users and Guests can manage own data" ON public.chat_messages;
CREATE POLICY "Users and Guests can manage own data" 
    ON public.chat_messages FOR ALL 
    USING (
        (auth.uid() = user_id) OR 
        (guest_session_id IS NOT NULL AND guest_session_id = current_setting('app.guest_session_id', true))
    );

-- Indices
CREATE INDEX IF NOT EXISTS chat_messages_user_id_created_at_idx ON public.chat_messages (user_id, created_at);
CREATE INDEX IF NOT EXISTS chat_messages_guest_session_idx ON public.chat_messages (guest_session_id, created_at);
